version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: grocery-tracker-db
    environment:
      POSTGRES_DB: grocery_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: