spring:
  application:
    name: grocery-tracker-spring
  data:
    rest:
      base-path: /api
      default-page-size: 20
      max-page-size: 100
      return-body-on-create: true
      return-body-on-update: true
  datasource:
    url: jdbc:postgresql://localhost:5432/grocery_tracker
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration